<?php
/**
 * @file
 * Code for the Feature Server UI feature.
 */

include_once 'fserver_ui.features.inc';

/**
 * Implements hook_form_alter().
 */
function fserver_ui_form_eck__entity__form_add_project_module_alter(&$form, &$form_state, $form_id) {
  dpm('alter!');
}

/**
 * Implements hook_form_alter().
 */
function fserver_ui_form_eck__entity__form_add_release_release_alter(&$form, &$form_state) {

  $form['project_short_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Project Short Name'),
    '#description' => t('Machine-name of the project for this release.'),
    '#size' => 40,
    '#maxlength' => 255,
  );

  $form['api'] = array(
    '#type' => 'textfield',
    '#title' => t('API'),
    '#description' => t('API version (i.e. 7.x)'),
    '#size' => 5,
    '#maxlength' => 4,
    // @todo add element validator
  );

  $form['version_major'] = array(
    '#type' => 'textfield',
    '#title' => t('Version Major'),
    '#size' => 3,
    '#maxlength' => 3,
    // @todo change to numberfield
  );

  $form['version_patch'] = array(
    '#type' => 'textfield',
    '#title' => t('Version Patch'),
    '#size' => 6,
    '#maxlength' => 4,
  );
  
  $form['version_extra'] = array(
    '#type' => 'textfield',
    '#title' => t('Version Extra'),
    '#description' => t('Ex: dev, alpha1'),
    '#size' => 40,
    '#maxlength' => 255,
  );  
  
  // Disable the title field
  $form['name']['#disabled'] = TRUE;
  
  $form['#submit'][] = 'fserver_ui_release_form_submit';
}

/**
 * Submit callback
 */
function fserver_ui_release_form_submit(&$form, &$form_state) {
  dpm('submit!');
}