<?php

/**
 * @file
 * Feature Server - Services integration
 */

/**
 * Implements hook_services_resources().
 */
function fserver_services_resources() {
  $resources = array();

  // Project resource
  $resources['project'] = array(
    'operations' => array(
      'retrieve' => array(
        'file' => array(
          'type' => 'inc',
          'module' => 'fserver_services',
          'name' => 'resources/fserver_services.project'
        ),
        'access callback' => '_fserver_services_access',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
        'callback' => '_fserver_services_retrieve_project',
        'args' => array(
          array(
            'name' => 'short_name',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The short name (i.e. machine name) of a project.',
          ),
          array(
            'name' => 'api',
            'optional' => FALSE,
            'source' => array('path' => 1),
            'description' => 'API version compatibility',
          ),
        ),
      ),
      //'create' => array(),
      //'update' => array(),
      //'delete' => array(),
      //'index' => array(),
    ),
    //'targeted_actions' => array(),
    //'relationships' => array(),
  );

  // Release resource
  $resources['release'] = array(
    'operations' => array(
      'retrieve' => array(),
      'create' => array(),
      'update' => array(),
      'delete' => array(),
      'index' => array(),
    ),
    'targeted_actions' => array(),
    'relationships' => array(),
  );

  return $resources;
}

/**
 * Add a response formatter for .x (since update paths end with the API version)
 */
function fserver_services_rest_server_response_formatters_alter(&$formatters) {
  $formatters['x'] = $formatters['xml'];
}

function _fserver_services_access($op) {
  return TRUE;
}