<?php

/**
 * @file
 * Feature Server - Services integration
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function fserver_services_ctools_plugin_api($module, $api) {
  if ($module == 'services' && $api == 'services') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_services_resources().
 */
function fserver_services_resources() {
  $resources = array();

  // Project resource
  $resources['project'] = array(
    'operations' => array(
      'retrieve' => array(
        'file' => array(
          'type' => 'inc',
          'module' => 'fserver_services',
          'name' => 'resources/fserver_services.project'
        ),
        'access callback' => '_fserver_services_access',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
        'callback' => '_fserver_services_retrieve_project',
        'args' => array(
          array(
            'name' => 'short_name',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The short name (i.e. machine name) of a project.',
          ),
        ),
      ),
      //'create' => array(),
      //'update' => array(),
      //'delete' => array(),
      //'index' => array(),
    ),
  );

  // Release resource
  $resources['release'] = array(
    'operations' => array(
      'retrieve' => array(),
      'create' => array(),
      'update' => array(),
      'delete' => array(),
      'index' => array(),
    ),
    'targeted_actions' => array(),
    'relationships' => array(),
  );

  // Release History
  $resources['release-history'] = array(
    'operations' => array(
      'retrieve' => array(
        'file' => array(
          'type' => 'inc',
          'module' => 'fserver_services',
          'name' => 'resources/fserver_services.release_history'
        ),
        'help' => t('Project release history XML feed.'),
        'access callback' => '_fserver_services_access',
        'access arguments' => array('release-history'),
        'access arguments append' => TRUE,
        'callback' => '_fserver_services_release_history',
        'args' => array(
          array(
            'name' => 'short_name',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
            'description' => 'The short name (i.e. machine name) of a project.',
          ),
          array(
            'name' => 'api',
            'optional' => FALSE,
            'source' => array('path' => 1),
            'description' => 'API version compatibility',
          ),
        ),
      ),
    ),
  );

  return $resources;
}

/**
 * Implements hook_rest_server_response_formatters_alter().
 * 
 * Add a response formatter for .x (since update paths end with the API version)
 */
function fserver_services_rest_server_response_formatters_alter(&$formatters) {
  $formatters['x'] = $formatters['xml'];
  $formatters['x']['formatter class'] = 'FeatureServerProjectXMLFormatter';
}

/**
 * Access callback for Feature Server services
 *
 * @param string $op
 *  Operation
 * @return boolean
 *  Return TRUE to grant access, FALSE otherwise.
 */
function _fserver_services_access($op) {
  return TRUE;
}